all.out:circle.h test_circle.cpp rectangle.h test_rectangle.cpp
	g++ circle.h test_circle.cpp rectangle.h test_rectangle.cpp -lgtest_main -lgtest -lpthread -o all.out
test:
	./all.out
clean:
	rm  *.out
